### ISSUE TITLE
static degisken

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/hasan_ali_ozdemir_onboarding_login#1]
burdaki flex degerini sayfa basında int  _flexMinValue = 1; şeklinde tanımlayıp ortaklaştırma yapmalıyız
https://github.com/VBT-FlutterCamp/hasan_ali_ozdemir_onboarding_login/blob/2ba20e07f4a4448ad531ce9bc2e50a410cbf9285/lib/view/onboarding/onboarding_view.dart#L80

**Comment by hasanaliozdemir** [comment]
Refactor işlemi yaparken bahsettiğin değişiklikleri de ekledim 😊
